# Netlify Configuration
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20.19.0"
  # Ensure devDependencies and optional native binaries install during npm ci
  NPM_FLAGS = "--legacy-peer-deps --include=dev --include=optional"
  npm_config_production = "false"
  npm_config_optional = "true"

# Production context: all deploys from the main branch
[context.production]
  command = "npm ci && npm run build"

# Deploy Preview context: all deploys from pull requests
[context.deploy-preview]
  command = "npm ci && npm run build"

# Branch deploy context: all deploys from branches that aren't main
[context.branch-deploy]
  command = "npm ci && npm run build"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# WASM MIME Type - Critical for sql.js to work
[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/wasm/*"
  [headers.values]
    Content-Type = "application/wasm"
    Cache-Control = "public, max-age=31536000, immutable"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=()"
    
    # Content Security Policy - Updated to allow WASM
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://ssl.google-analytics.com https://apis.google.com https://www.gstatic.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https: blob:;
      font-src 'self' data: https://fonts.gstatic.com;
      connect-src 'self' https://*.firebase.googleapis.com https://*.firebaseio.com https://www.google-analytics.com https://firebase.googleapis.com wss://*.firebaseio.com;
      frame-src 'self' https://www.google.com https://accounts.google.com https://*.firebaseapp.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
    """
    
    # HSTS - Strict Transport Security
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Service Worker - should not be cached
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"
    Content-Type = "application/manifest+json"

# HTML - short cache
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

# Images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions (if you add them later)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.85
    accessibility = 0.90
    best-practices = 0.85
    seo = 0.90
    pwa = 0.80

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://protegelecture.org"
    sitemapPath = "/sitemap.xml"
    providers = [
      "google",
      "bing"
    ]
